version: "3.9"
services:
  client:
    build: ./client
    container_name: 'planning-poker-client'
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  server:
    build: ./server
    container_name: 'planning-poker-server'
    command: '/usr/src/app/node_modules/nodemon/bin/nodemon.js app.js'
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    # links:
    #   - redis

  # redis:
    # image: redis
