version: "3.9"
services:
  client:
    build: ./client
    container_name: 'planning-poker-client'
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - client-volume:/usr/src/app/node_modules

  server:
    build: ./server
    container_name: 'planning-poker-server'
    command: '/usr/src/app/node_modules/nodemon/bin/nodemon.js app.js'
    ports:
      - '3001:3001'
    volumes:
      - ./server:/usr/src/app
      - server-volume:/usr/src/app/node_modules
    links:
      - redis-cache
    environment:
      # Matches the service name below
      - REDIS_URL=redis-cache

  redis-cache:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'

volumes:
  client-volume:
  server-volume:
